FROM ubuntu:22.04
MAINTAINER EdwardArutyunyan
LABEL prometheus=v1.2

# Install extra soft
RUN apt-get update \
 && apt install -y nano \
                   wget \
                   \
 && apt-get -q -y clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/apt

# install Prometheus 2.40
RUN wget https://github.com/prometheus/prometheus/releases/download/v2.40.5/prometheus-2.40.5.linux-386.tar.gz \
 &&  tar xvf prometheus-2.40.5.linux-386.tar.gz && cp prometheus-2.40.5.linux-386/prometheus /usr/local/bin && cp prometheus-2.40.5.linux-386/promtool /usr/local/bin \
 && mkdir /etc/prometheus && cp -r prometheus-2.40.5.linux-386/consoles /etc/prometheus && cp -r prometheus-2.40.5.linux-386/console_libraries /etc/prometheus \
 && rm -r prometheus-2.40.5.linux*



# Copy configs
COPY prometheus_rules.yml /etc/prometheus
COPY prometheus.yml /etc/prometheus

# Choose defauld directory
WORKDIR /etc/prometheus

# Create directory for TSDB
RUN mkdir /prometheus

# Open port
expose 9090

# Docker start  & choose options
ENTRYPOINT [ "/usr/local/bin/prometheus" ]
CMD        [ "--config.file=/etc/prometheus/prometheus.yml", \
             "--storage.tsdb.path=/prometheus", \
             "--storage.tsdb.retention.time=45d" ]
